package com.csusb.cse455.trip.model;

// User's trip data item.
public class MyTripItem {
    // Trip's unique ID generated by the database.
    private String mId;
    // Trip's unique label created by the user.
    private String mLabel;
    // Trip's description provided by the user.
    private String mDescription;

    // Returns trip ID.
    public String getId() {
        return mId;
    }

    // Sets trip ID.
    public void setId(String id) {
        this.mId = id;
    }

    // Gets trip label.
    public String getLabel() {
        return mLabel;
    }

    // Sets trip label.
    public void setLabel(String label) {
        this.mLabel = label;
    }

    // Returns trip description.
    public String getDescription() {
        return mDescription;
    }

    // Sets trip description.
    public void setDescription(String description) {
        this.mDescription = description;
    }
}
