package com.csusb.cse455.trip.model;

import android.media.Image;

// User's trip data item.
public class Trip {
    // Trip's unique ID generated by the database.
    private String mId;
    // Trip's unique label created by the user.
    private String mLabel;
    // Trip's description provided by the user.
    private String mDescription;
    // Trip's owner ID.
    private String mOwnerId;
    // Snapshot image, which is a visual overview of the trip.
    private Image mSnapshot;
    // Trip route.
    private Route mRoute;

    // Default constructor.
    public Trip() {
        // To avoid having a null locations list.
        mRoute = new Route();
    }

    // Overloaded constructor.
    public Trip(Route route) { mRoute = route; }

    // Returns trip ID.
    public String getId() {
        return mId;
    }

    // Sets trip ID.
    public void setId(String id) {
        this.mId = id;
    }

    // Gets trip label.
    public String getLabel() {
        return mLabel;
    }

    // Sets trip label.
    public void setLabel(String label) {
        this.mLabel = label;
    }

    // Returns trip description.
    public String getDescription() {
        return mDescription;
    }

    // Sets trip description.
    public void setDescription(String description) {
        this.mDescription = description;
    }

    // Returns owner's id.
    public String getOwnerId() { return mOwnerId; }

    // Sets owner's id.
    public void setOwnerId(String id) { mOwnerId = id; }

    // Returns trip snapshot.
    public Image getSnapshot() { return mSnapshot; }

    // Sets trip snapshot.
    public void setSnapshot(Image snapshot) { mSnapshot = snapshot; }

    // Returns trip route.
    public Route getLocations() { return mRoute; }

    // Sets trip route.
    public void setLocations(Route route) { mRoute = route; }
}
